version: 2
jobs:
  build:    
    docker:
      - image: cirrusci/flutter:v1.18.0-dev5.0

    branches:
      only: develop

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

      - run:
          name: Build the Android version
          command: flutter build apk